# Generated by Django 4.0.4 on 2022-07-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact_alter_articles_likes_alter_comments_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tagline',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
    ]
