# Generated by Django 4.0.4 on 2022-11-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articles_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
    ]
