# Generated by Django 3.2.19 on 2023-05-22 08:53

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('blog', '0003_articles_password_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('philosophy and life reflections', 'Philosophy and life reflections'), ('personal development and growth', 'Personal development and growth'), ('social and cultural commentary', 'Social and Cultural commentary'), ('inspirational stories', 'Inspirational stories'), ('mindfulness and well being', 'Mindfulness and Well being')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
