# Generated by Django 3.2.19 on 2023-05-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230522_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='post_medium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('plr', 'Philosophy and life reflections'), ('pdg', 'Personal development and growth'), ('scc', 'Social and Cultural commentary'), ('ins', 'Inspirational stories'), ('mwb', 'Mindfulness and Well being')], max_length=200),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tagline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
