# Generated by Django 4.0.4 on 2022-11-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comments_name_applaud'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='applaud',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Applaud',
        ),
    ]
