# Generated by Django 3.2.19 on 2023-05-24 16:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_newsletteremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
