# Generated by Django 3.2.19 on 2023-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_articles_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
