# Generated by Django 3.2.19 on 2023-06-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articles_meta_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
