# Generated by Django 3.2.19 on 2023-06-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('plr', 'Philosophy and life reflections'), ('pdg', 'Personal development and growth'), ('scc', 'Social and Cultural commentary'), ('ins', 'Inspirational stories'), ('mwb', 'Mindfulness and Well being'), ('bks', 'Book Reviews')], max_length=200),
        ),
    ]
