# Generated by Django 4.0.4 on 2022-06-19 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0002_podcomments_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodes',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='podliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podcomments',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='podcomment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PodLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.episodes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
