# Generated by Django 4.0.4 on 2022-06-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_episodes_likes_alter_podcomments_author_podlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podlike',
            old_name='article',
            new_name='episode',
        ),
    ]
