# Generated by Django 4.0.4 on 2022-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_podcomments_spotifylink_alter_podcomments_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcomments',
            name='spotifylink',
        ),
        migrations.AddField(
            model_name='episodes',
            name='spotifylink',
            field=models.CharField(default='1jQnF8PfdpYKo9Jguhinlc', max_length=200),
        ),
    ]
